- CHANGELOG.md
- src/API.ts
- src/RoomClient.ts
- src/useConnectCall.ts
The server stopped implementing `authenticate` in the JWT transition, and now we no longer need to send it.
> remove deprecated authenticate event

- CHANGELOG.md
- src/RoomClient.ts
- src/__mocks__/MediaDevices.ts
- src/useConnectCall.test.ts
- src/useConnectCall.ts
Previously `useConnectCall` took the liberty of automatically producing a video and audio track during the connection process. Now it is the responsibility of the caller.
This was the only way I could see to support react-native-webrtc without adding the dependency for web clients. It also removes the need to understand call types and user roles, because all of that is effectively pushed out to the caller.
Long term this should also make it easier to provide controls for users to choose audio or video devices.
> make caller responsible for producing tracks

- src/useConnectCall.ts
This is a remnant from when CVH used Malan session tokens.
> stop asking for unused authInfo.token

- CHANGELOG.md
- src/useConnectCall.test.ts
- src/useConnectCall.ts
Applications may want to tear down the video call state without unmounting whatever component calls `useConnectCall`. The `disconnect()` function aims to provide that ability. It also means a new ClientState.
> return a disconnect() function

- CHANGELOG.md
- src/API.ts
- src/RoomClient.ts
I've come to believe that our heartbeat implementation is [redundant with socket.io's protocol](https://socket.io/blog/engine-io-4-release/#heartbeat-mechanism-reversal). Nevertheless, it seems easier to implement support now rather than gather buy-in for the change to CVH.
> implement heartbeat

- tsconfig.build.json
I confirmed locally that this fixes the need for `jest.transformIgnorePatterns` when running Jest tests in the host application.
> build CommonJS for Jest compatibility

- CHANGELOG.md
- tsconfig.build.json
Source maps create confusion (and warnings) without the accompanying source. However, shipping the source to an unknown toolchain does not make sense. Removing source maps will mean that stack traces blame the compiled code, which seems acceptable.
> remove source maps from compilation

- package-lock.json
- src/useConnectCall.ts
In react strict mode, components get rendered twice. This caused a problem in `ameelio-web` where `useConnectCall` was called twice and, when the first room was `close()`-d, the new room's produce got interrupted. Adds a 10ms delay to `useConnectCall` before actually attempting to connect to avoid this.
> Add debounce delay for react strict mode compatibility

- CHANGELOG.md
- README.md
- src/RoomClient.ts
I began receiving the following error during test calls. It appears to represent an incompatibility with Chrome. I relaunched Chrome recently and am now running v111. Older versions may not yet experience problems.
> Produce error: DOMException: Failed to execute 'addTransceiver' on 'RTCPeerConnection': Attempted to set RtpParameters scalabilityMode to an unsupported value for the current codecs.
According to https://w3c.github.io/webrtc-svc/#scalabilitymodes*, `S1T3` is not a valid identifier. According to the naming convention, `S1` would mean "1 spatial layer" which is equivalent to `L1`. Thus `L1T3` appears to be the correct identifier. This is further corroborated by recent updates to mediasoup-demo's simulcast configuration.
> fix scalabilityMode with VP8

- package-lock.json
- package.json
- src/API.ts
- src/Client.ts
- src/RoomClient.ts
- src/__mocks__/MediaDevices.ts
- src/__mocks__/mediasoup-client.ts
- src/testFactories.ts
- src/useConnectCall.test.ts
- src/useConnectCall.ts
1. Now responds to "statusUpdate" to change its local muted status to respect remote mutes. (For privacy reasons. Otherwise it would get recorded even though nobody can hear.)
2. Exposed "submitOperation" function for remote muting and later extensions.
> Remote muting and new socket events

- src/RoomClient.ts
- src/testFactories.ts
- src/useConnectCall.test.ts
- src/useConnectCall.ts
Took a while to figure out what was causing this. The initial `status` of peers is sent over in the `joined` event, which is sent immediately after the `join` request is made with good credentials, _before_ the request is even responded to or the rest of the handshake is done. This means that the `RoomClient` has not initialized yet when the `joined` event fires and we don't hear about the initial status of peers.
I tried a couple workarounds and this one seemed to require the least refactoring -- we listen for `joined` events before sending `join` and "stage" them so that they can be responded to immediately once the `RoomClient` is done handshaking.
> Track initial status

- CHANGELOG.md
- package.json
- src/RoomClient.ts
- src/useConnectCall.test.ts
- src/useConnectCall.ts
Formerly we detected whether a participant was muted by checking whether the audio track existed. This fails to distinguish between _paused_ audio and _broken_ audio. Since we're modifying connect-call-client now anyway I figured we should expose information about consumer paused states to fix this.
> Expose paused states of streams

- src/API.ts
- src/RoomClient.ts
- src/useConnectCall.ts
The client mute status should always track the server mute status. We might be initialized with the server mute status on, which caused a problem because the tracking only responded to changes and initialized unmuted. Fixes this by initializing muted.
TODO in a later PR: figure out how to handle the fact that non-hosts are probably forbidden from screensharing.
> Respect server mutes immediately

- src/RoomClient.ts
- src/useConnectCall.ts
This is needed to have the disableFrux setting respond to our webinar role.
> Allow setting disable frux dynamically

- src/RoomClient.ts
- src/__mocks__/MediaDevices.ts
- src/__mocks__/MediaStream.ts
I noticed that once I started screensharing I couldn't stop. That's what `closeProducer` was for but nobody ever called it. This will call it when the track ends, which will happen when a user clicks "stop screensharing" in the native browser UI.
> Automatically close producer when track ends

- src/useConnectCall.ts
Previously a missing useEffect dependencies meant that `setDisableFrux` did nothing if called too early.
> Allow disabling frux before client is initialized

- package-lock.json
- package.json
- src/RoomClient.ts
- src/useConnectCall.ts
As per discussion in slack. Stores monitors in a separate array; only stores ids because monitors don't really have any other state (streams, statuses).
> Separate monitor join/disconnect events

- .eslintrc.js
- package.json
- src/API.ts
- src/Client.ts
- src/RoomClient.ts
- src/__mocks__/Client.ts
- src/__mocks__/MediaStream.ts
- src/__mocks__/mediasoup-client.ts
- src/testFactories.ts
- src/useConnectCall.test.ts
- src/useConnectCall.ts
Internally, have refactored `RoomClient` to expose updates in the following form:
- `peers` -- publishes entire `peers` object at once.
- `self` -- publishes self as a `Peer` object
- `status` -- publishes room status
Externally, have changed the api in a variety of ways:
1. Instead of `localVideo`, `localAudio`, and `Peer.video`, `Peer.audio`, we have structs `localProducers` and `Peer.consumers`, of type `Partial<ProducerLabel, { stream: MediaStream; paused: boolean }>`.
2. Similarly `toggleVideo/toggleAudio` has been replaced by generic `pausedProducer` and `resumeProducer` which take `ProducerLabel` arguments.
3. The exposed `peers` are now an object `{ [socketId: string]: Peer }` instead of an array `Peer[]`. I don't believe anyone actually needs to know the `socketId` but it will …
> Use state event

- CHANGELOG.md
- src/API.ts
- src/RoomClient.ts
- src/useConnectCall.ts
1. Whenever socket.io disconnects and reconnects, also shut down old mediasoup streams and creating new ones.
2. Add provisions for manual disconnection where the server can send a reason. When this happens, don't automatically reconnect, but force the application layer to call `manuallyReconnect`, which will presumably be activated by a user action.
> Handle disconnects

- src/useConnectCall.ts
[sc-6483]
For some operations, like messaging, it makes sense to just disable it while you don't have internet. For others, like video/audio mute/unmute, one can imagine that a user might need to do this while disconnected (especially muting) with the expectation that the change gets applied when they reconnect. This PR should make this possible.
> Use track.enabled to pause/resume while not connected

- src/useConnectCall.ts
Trying to make this part of 2.4.0; lint caught a missing hook dependency that I think could've caused problems.
> Fix callback dependency issue caught by lint

- package-lock.json
Fixes https://github.com/advisories/GHSA-67hx-6x53-jw92
Steps I followed:
1. delete `node_modules/@babel/traverse` and `@babel/traverse` from `package-lock.json`
2. `npm install` to resolve missing packages
3. verify that package-lock.json resolved `@babel/traverse` to `7.23.2`
> update @babel/traverse to 7.23.2
